In [4]:
import yfinance as yf
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import pandas as pd

In [11]:
#pip install pyarrow fastparquet

Collecting pyarrow
  Downloading pyarrow-14.0.1-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (3.0 kB)
Collecting fastparquet
  Downloading fastparquet-2023.10.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.1 kB)
Requirement already satisfied: numpy>=1.16.6 in /home/pedro/miniconda3/envs/AulasMachineLearning/lib/python3.12/site-packages (from pyarrow) (1.26.2)
Requirement already satisfied: pandas>=1.5.0 in /home/pedro/miniconda3/envs/AulasMachineLearning/lib/python3.12/site-packages (from fastparquet) (2.1.3)
Collecting cramjam>=2.3 (from fastparquet)
  Downloading cramjam-2.7.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.0 kB)
Collecting fsspec (from fastparquet)
  Downloading fsspec-2023.10.0-py3-none-any.whl.metadata (6.8 kB)
Requirement already satisfied: packaging in /home/pedro/miniconda3/envs/AulasMachineLearning/lib/python3.12/site-packages (from fastparquet) (23.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/pedro/miniconda3/envs/AulasMachineLearning/lib/python3.12/site-packages (from pandas>=1.5.0->fastparquet) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /home/pedro/miniconda3/envs/AulasMachineLearning/lib/python3.12/site-packages (from pandas>=1.5.0->fastparquet) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /home/pedro/miniconda3/envs/AulasMachineLearning/lib/python3.12/site-packages (from pandas>=1.5.0->fastparquet) (2023.3)
Requirement already satisfied: six>=1.5 in /home/pedro/miniconda3/envs/AulasMachineLearning/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas>=1.5.0->fastparquet) (1.16.0)
Downloading pyarrow-14.0.1-cp312-cp312-manylinux_2_28_x86_64.whl (38.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 38.0/38.0 MB 451.4 kB/s eta 0:00:0000:0100:03
Downloading fastparquet-2023.10.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 1.7 MB/s eta 0:00:0000:0100:01
Downloading cramjam-2.7.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 1.9 MB/s eta 0:00:0000:0100:01
Downloading fsspec-2023.10.0-py3-none-any.whl (166 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 166.4/166.4 kB 958.1 kB/s eta 0:00:00 0:00:01
Installing collected packages: pyarrow, fsspec, cramjam, fastparquet
Successfully installed cramjam-2.7.0 fastparquet-2023.10.1 fsspec-2023.10.0 pyarrow-14.0.1

In [5]:
symbols = ['BTC-USD', 'ETH-USD', 'USDT-USD', 'SOL-USD', 'DOGE-USD']
start_date = '2018-01-01'
end_date = '2023-11-29'

In [13]:
lista_dfs = []
path = '/home/pedro/AulaMachineLearning/machinelearning/data/raw/'
for symbol in symbols:
    temp_path = path+symbol+'.parquet.gzip'
    df = yf.download(symbol, start=start_date, end=end_date)
    df.to_parquet(temp_path, compression='gzip')

[*********************100%%**********************]  1 of 1 completed

[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed

[                    Open          High           Low         Close  \
 Date
 2018-01-01  14112.200195  14112.200195  13154.700195  13657.200195
 2018-01-02  13625.000000  15444.599609  13163.599609  14982.099609
 2018-01-03  14978.200195  15572.799805  14844.500000  15201.000000
 2018-01-04  15270.700195  15739.700195  14522.200195  15599.200195
 2018-01-05  15477.200195  17705.199219  15202.799805  17429.500000
 ...                  ...           ...           ...           ...
 2023-11-24  37296.316406  38415.339844  37261.605469  37720.281250
 2023-11-25  37721.414062  37892.429688  37617.417969  37796.792969
 2023-11-26  37796.828125  37820.300781  37162.750000  37479.121094
 2023-11-27  37454.191406  37559.355469  36750.128906  37254.167969
 2023-11-28  37247.992188  38368.480469  36891.089844  37831.085938

                Adj Close       Volume
 Date
 2018-01-01  13657.200195  10291200000
 2018-01-02  14982.099609  16846600192
 2018-01-03  15201.000000  16871900160
 2018-01-04  15599.200195  21783199744
 2018-01-05  17429.500000  23840899072
 ...                  ...          ...
 2023-11-24  37720.281250  22922957823
 2023-11-25  37796.792969   9099571165
 2023-11-26  37479.121094  13744796068
 2023-11-27  37254.167969  19002925720
 2023-11-28  37831.085938  21696137014

 [2158 rows x 6 columns],
                    Open         High          Low        Close    Adj Close  \
 Date
 2018-01-01   755.757019   782.530029   742.004028   772.640991   772.640991
 2018-01-02   772.346008   914.830017   772.346008   884.443970   884.443970
 2018-01-03   886.000000   974.471008   868.450989   962.719971   962.719971
 2018-01-04   961.713013  1045.079956   946.085999   980.921997   980.921997
 2018-01-05   975.750000  1075.390015   956.325012   997.719971   997.719971
 ...                 ...          ...          ...          ...          ...
 2023-11-24  2062.411865  2132.481201  2060.999023  2081.152100  2081.152100
 2023-11-25  2081.296143  2091.342773  2067.917236  2084.413086  2084.413086
 2023-11-26  2084.177490  2094.095947  2038.600464  2063.286133  2063.286133
 2023-11-27  2062.390869  2070.606201  1988.120361  2027.417358  2027.417358
 2023-11-28  2027.517212  2074.954102  1996.814697  2049.338135  2049.338135

                  Volume
 Date
 2018-01-01   2595760128
 2018-01-02   5783349760
 2018-01-03   5093159936
 2018-01-04   6502859776
 2018-01-05   6683149824
 ...                 ...
 2023-11-24  12141148820
 2023-11-25   5362623390
 2023-11-26   8054814154
 2023-11-27  10574810069
 2023-11-28   9910633038

 [2158 rows x 6 columns],
                 Open      High       Low     Close  Adj Close       Volume
 Date
 2018-01-01  1.012550  1.015360  1.001530  1.007280   1.007280   1685299968
 2018-01-02  1.005740  1.009880  0.993250  1.004900   1.004900   2635859968
 2018-01-03  1.006600  1.023280  1.002640  1.013440   1.013440   2471689984
 2018-01-04  1.013200  1.016180  0.993822  1.002530   1.002530   3200130048
 2018-01-05  1.001750  1.005010  0.985915  0.998634   0.998634   3096620032
 ...              ...       ...       ...       ...        ...          ...
 2023-11-24  1.000149  1.000858  0.999923  1.000353   1.000353  40071555958
 2023-11-25  1.000264  1.000817  0.999926  1.000479   1.000479  23045093192
 2023-11-26  1.000486  1.000609  0.999623  1.000211   1.000211  30299804822
 2023-11-27  1.000214  1.000661  0.999835  0.999980   0.999980  38568585545
 2023-11-28  1.000112  1.000668  0.999888  1.000377   1.000377  37720536626

 [2158 rows x 6 columns],
                  Open       High        Low      Close  Adj Close      Volume
 Date
 2020-04-10   0.832005   1.313487   0.694187   0.951054   0.951054    87364276
 2020-04-11   0.951054   1.049073   0.765020   0.776819   0.776819    43862444
 2020-04-12   0.785448   0.956670   0.762426   0.882507   0.882507    38736897
 2020-04-13   0.890760   0.891603   0.773976   0.777832   0.777832    18211285
 2020-04-14   0.777832   0.796472   0.628169   0.661925   0.661925    16747614
 ...               ...        ...        ...        ...        ...         ...
 2023-11-24  56.578892  58.686012  56.349091  56.866440  56.866440  1146346831
 2023-11-25  56.866287  59.654144  56.325279  58.846489  58.846489  1183793273
 2023-11-26  58.845421  58.957962  56.511456  57.642700  57.642700   871154750
 2023-11-27  57.628868  58.021225  53.714470  55.064621  55.064621  1237763215
 2023-11-28  55.062630  58.606823  54.085323  58.194370  58.194370  1412314015

 [1328 rows x 6 columns],
                 Open      High       Low     Close  Adj Close     Volume
 Date
 2018-01-01  0.009031  0.009063  0.008101  0.008909   0.008909   50616900
 2018-01-02  0.008873  0.009598  0.008551  0.009145   0.009145   89424096
 2018-01-03  0.009088  0.009584  0.008882  0.009320   0.009320   66349900
 2018-01-04  0.009346  0.010036  0.008768  0.009644   0.009644  108986000
 2018-01-05  0.009660  0.012283  0.009589  0.012167   0.012167  212383008
 ...              ...       ...       ...       ...        ...        ...
 2023-11-24  0.076199  0.078429  0.076149  0.078217   0.078217  401116993
 2023-11-25  0.078216  0.079105  0.077763  0.078955   0.078955  291859035
 2023-11-26  0.078952  0.078980  0.076346  0.078704   0.078704  343339848
 2023-11-27  0.078690  0.081320  0.077089  0.078788   0.078788  743996999
 2023-11-28  0.078792  0.081031  0.077037  0.081009   0.081009  618900678

 [2158 rows x 6 columns]]

In [14]:
path_local = '/home/pedro/AulaMachineLearning/machinelearning/data/raw/BTC-USD.parquet.gzip'

In [15]:
df = pd.read_parquet(path_local)

In [16]:
df

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2018-01-01,14112.200195,14112.200195,13154.700195,13657.200195,13657.200195,10291200000
2018-01-02,13625.000000,15444.599609,13163.599609,14982.099609,14982.099609,16846600192
2018-01-03,14978.200195,15572.799805,14844.500000,15201.000000,15201.000000,16871900160
2018-01-04,15270.700195,15739.700195,14522.200195,15599.200195,15599.200195,21783199744
2018-01-05,15477.200195,17705.199219,15202.799805,17429.500000,17429.500000,23840899072
...,...,...,...,...,...,...
2023-11-24,37296.316406,38415.339844,37261.605469,37720.281250,37720.281250,22922957823
2023-11-25,37721.414062,37892.429688,37617.417969,37796.792969,37796.792969,9099571165
2023-11-26,37796.828125,37820.300781,37162.750000,37479.121094,37479.121094,13744796068
2023-11-27,37454.191406,37559.355469,36750.128906,37254.167969,37254.167969,19002925720
2023-11-28,37247.992188,38368.480469,36891.089844,37831.085938,37831.085938,21696137014